[package]
name = "vetis-wt"
version = "0.1.0-beta.1"
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Very Tiny Server WebTransport support"
readme = "README.md"
license.workspace = true
keywords = ["http", "modules", "webtransport", "vetis"]
publish = true
rust-version.workspace = true

[features]
default = ["runtime-tokio"]

runtime-tokio = ["dep:tokio"]

[dependencies]
base64 = "0.23.1"
h3-webtransport = "0.1.2"
http.workspace = true
hyper = { version = "1.11.1", default-features = false, features = [
    "http1",
    "server",
] }
hyper-body-utils = { version = "0.1.17", default-features = false, features = [
    "generic",
] }
hyper-util = { version = "0.1.21", default-features = false, features = [
    "server",
    "http1",
    "tokio",
] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { workspace = true, optional = true }
typetag = "0.2.21"
vetis.workspace = true

[dev-dependencies]
caramelo = "0.1.5"
deboa.workspace = true
deboa-tokio = { workspace = true, default-features = false, features = [
    "http3",
    "rust-tls",
    "default-rustls-provider",
    "default-rustls-verifier",
] }
serde_yaml_ng = "0.10.0"
tokio = { workspace = true, default-features = false, features = ["macros"] }
vetis-tokio = { workspace = true, features = ["http3", "rust-tls"] }
