[package]
name = "vetis-rsgi"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Very Tiny Server RSGI support"
readme = "README.md"
license.workspace = true
keywords = ["http", "modules", "server", "rest-server"]
publish = true
rust-version.workspace = true

[features]
default = []

[dependencies]
http.workspace = true
hyper-body-utils.workspace = true
pyo3 = "0.29.0"
vetis = { path = "../../vetis/vetis" }
vetis-tokio = { path = "../../vetis-tokio", optional = true, default-features = false }
