[package]
name = "vetis-flash"
version = "0.1.1-beta.1"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Very Tiny Server Flash Static Content support"
readme = "README.md"
license.workspace = true
keywords = ["http", "modules", "server", "rest-server"]
publish = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = ["runtime-tokio"]
runtime-tokio = ["vetis-tokio/rust-tls", "dep:tokio"]

[dependencies]
duration-str = "0.21.0"
http.workspace = true
hyper-body-utils.workspace = true
log.workspace = true
regex = "1.12.4"
#send_wrapper = "0.6.0"
serde = { version = "1.0.228", features = ["derive"] }
time = "0.3.55"
tokio = { workspace = true, optional = true }
typetag.workspace = true
vetis.workspace = true
#vetis-compio = { version = "0.1.0", optional = true, default-features = false }
#vetis-smol = { version = "0.1.0", optional = true, default-features = false }
vetis-tokio = { workspace = true, optional = true, default-features = false }
upon = "0.11.0"

[dev-dependencies]
caramelo = "0.1.5"
compio = { version = "0.19.2", default-features = false }
deboa.workspace = true
# deboa-compio = { version = "0.1.1", default-features = false, features = [
#   "http2",
#   "rust-tls",
#   "default-rustls-provider",
#   "default-rustls-verifier",
# ] }
# deboa-smol = { version = "0.1.1", default-features = false, features = [
#   "http2",
#   "rust-tls",
#   "default-rustls-provider",
#   "default-rustls-verifier",
# ] }
deboa-tokio = { workspace = true, default-features = false, features = [
  "http2",
  "rust-tls",
  "default-rustls-provider",
  "default-rustls-verifier",
] }
serde_yaml_ng = "0.10.0"
tokio = { version = "1.52.3", default-features = false, features = ["macros"] }
#vetis-macros = { path = "../../vetis/vetis-macros" }
vetis-macros = { version = "0.1.3-beta.5" }
