[workspace]
# Use the latest resolver available
resolver = "3"
# Include both parts of the library in the workspace
members = [
    "front",
    #"vetis-auth",
    #"vetis-asgi",
    #"vetis-fcgi",
    "vetis-proxy",
    "vetis-rev-proxy",
    #"vetis-rack",
    #"vetis-rsgi",
    #"vetis-sapi",
    #"vetis-scgi",
    "vetis-static",
    #"vetis-wsgi",
]

[workspace.package]
authors = ["Rogerio Araújo <rogerio.araujo@gmail.com>"]
edition = "2021"
repository = "https://github.com/vetis-server/vetis-extras"
homepage = "https://github.com/vetis-server/vetis-extras"
license = "MIT OR Apache-2.0"
rust-version = "1.75.0"

[workspace.dependencies]
#deboa = { path = "../deboa/deboa" }
deboa = { version = "0.1.5-beta.2" }
#deboa-tokio = { path = "../deboa-tokio/deboa-tokio", default-features = false }
deboa-tokio = { version = "0.1.4-beta.3", default-features = false }
http = "1.5.0"
hyper-body-utils = "0.1.17"
log = "0.4.33"
pyo3 = { version = "0.29.0", features = ["auto-initialize"] }
#vetis = { path = "../vetis/vetis" }
vetis = { version = "0.1.7-beta.1" }
vetis-static = { path = "vetis-static" }
#vetis-tokio = { path = "../vetis-tokio", optional = true, default-features = false }
vetis-tokio = { version = "0.1.2-beta.1", default-features = false }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
