[package]
name = "vetis-sapi"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
http.workspace = true
hyper-body-utils.workspace = true
log.workspace = true
ripht-php-sapi = "0.1.0-rc.9"
vetis = { path = "../../vetis/vetis" }
vetis-tokio = { path = "../../vetis-tokio", optional = true, default-features = false }
